[package]
name = "rusday"
version = "0.2.0"
authors = ["Johannes Christ <Johannes.christ@gmail.com>"]

[dependencies]
chrono = "0.4"
clap = "~2.29"

[dependencies.rusqlite]
version = "0.13.0"
features = ["chrono"]
